### ISSUE TITLE
Add capability to install a block-all firewall rule for a device in the event all white-list rules for a device do not match. 

### ISSUE THREAD

**Issue by kyeich** [osmud/osmud#67] opened 2018-07-13 15:55 UTC
The MUD file lists all the white-list rules. In order to deny traffic to other sites, we need a specific block rule installed. Firewall rule order is important.

**Comment by danweller18** [comment] 2018-07-20 09:24
Duplicate of #39

**Closed by danweller18** 2018-07-20 09:24 UTC
